package com.example.Practice_Security;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.http.client.HttpComponentsClientHttpRequestFactory;
import org.springframework.web.client.RestTemplate;

import static org.apache.tomcat.util.net.SocketEvent.TIMEOUT;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class PracticeSecurityApplication {
	public static void main(String[] args) {
		SpringApplication.run(PracticeSecurityApplication.class, args);
	}
}
